#pragma once

// YachtServiceClient.hpp -- the C++ counterpart of Yacht/Service References/.../Reference.cs.
//
// That file is generated by svcutil from the service's WSDL. There is no such generator here,
// so this is the same proxy written by hand against the same contract: one asynchronous method
// and one completion event per operation, over a SOAP channel.
//
// The endpoint and binding are the ones the original's ServiceReferences.ClientConfig names --
// basicHttpBinding to http://localhost:8888/GameServer/ -- which is also what the sample's own
// documentation tells the player to set up.

#include <exception>
#include <functional>
#include <mutex>
#include <optional>
#include <string>
#include <vector>

#include "SharpRuntime/SharpRuntimeHelper.hpp"
#include "System/Convert.hpp"
#include "System/EventArgs.hpp"
#include "System/EventHandler.hpp"
#include "System/Guid.hpp"
#include "System/Object.hpp"
#include "System/ServiceModel/BasicHttpBinding.hpp"
#include "System/ServiceModel/Channels/SoapChannel.hpp"
#include "System/ServiceModel/EndpointAddress.hpp"
#include "System/Threading/Tasks/Task.hpp"
#include "System/Uri.hpp"
#include "System/Xml/XmlWriter.hpp"

namespace YachtServices {

/** @brief The bytes a `byte[]` operation returned, or nothing when it returned null. */
using ByteArrayResult = std::optional<std::vector<SharpRuntime::bytecs>>;

/**
 * @brief What a completed operation reports back.
 *
 * The generated proxy declares one of these per operation -- `RegisterCompletedEventArgs`,
 * `JoinGameCompletedEventArgs` and so on -- differing only in the type of `Result`. They are
 * aliases of one template here rather than ten near-identical classes; the names callers use
 * are the generated ones.
 *
 * @tparam TResult What the operation returns.
 */
template <typename TResult>
class AsyncCompletedEventArgsT : public System::EventArgs {
public:
    /** @brief What the operation returned, meaningful only when Error is null. */
    TResult Result{};

    /** @brief What went wrong, or null when the operation succeeded. */
    std::exception_ptr Error;
};

/** @brief What a completed operation with no return value reports back. */
class AsyncCompletedEventArgs : public System::EventArgs {
public:
    /** @brief What went wrong, or null when the operation succeeded. */
    std::exception_ptr Error;
};

/** @brief Reports the session ID Register returned. */
using RegisterCompletedEventArgs = AsyncCompletedEventArgsT<int>;
/** @brief Reports whether the player was admitted to the game. */
using JoinGameCompletedEventArgs = AsyncCompletedEventArgsT<bool>;
/** @brief Reports whether the player was in a game to leave. */
using LeaveGameCompletedEventArgs = AsyncCompletedEventArgsT<bool>;
/** @brief Reports the serialized game state, or nothing when the game is gone. */
using GetGameStateCompletedEventArgs = AsyncCompletedEventArgsT<ByteArrayResult>;
/** @brief Reports the serialized list of joinable games. */
using GetAvailableGamesCompletedEventArgs = AsyncCompletedEventArgsT<ByteArrayResult>;
/** @brief Reports the new game's identifier, or nothing when it could not be created. */
using NewGameCompletedEventArgs = AsyncCompletedEventArgsT<ByteArrayResult>;
/** @brief Reports the player's score card. */
using GetScoreCardCompletedEventArgs = AsyncCompletedEventArgsT<ByteArrayResult>;
/** @brief Reports that the registration was dropped. */
using UnregisterCompletedEventArgs = AsyncCompletedEventArgs;
/** @brief Reports that the timeout was reset. */
using ResetTimeoutCompletedEventArgs = AsyncCompletedEventArgs;
/** @brief Reports that the step was recorded. */
using GameStepCompletedEventArgs = AsyncCompletedEventArgs;

/**
 * @brief An asynchronous proxy to the Yacht game server.
 *
 * @note **Completions are queued, not delivered where they finish.** Windows Phone's generated
 * proxy captures the caller's SynchronizationContext and raises the completion event back on
 * it, which is why the original's handlers can touch game state without a thought. CNA has no
 * such pump, so the work runs on a task and the completion is put on a queue that
 * `DispatchPendingCompletions` drains -- and the game drains it once per frame, on its own
 * thread. The effect is the original's: a handler never runs while a frame is half drawn.
 * Recorded in diff.md as the port's one threading deviation.
 */
class YachtServiceClient {
public:
    /** @brief Raised when Register finishes. */
    System::EventHandler<RegisterCompletedEventArgs> RegisterCompleted;
    /** @brief Raised when Unregister finishes. */
    System::EventHandler<UnregisterCompletedEventArgs> UnregisterCompleted;
    /** @brief Raised when JoinGame finishes. */
    System::EventHandler<JoinGameCompletedEventArgs> JoinGameCompleted;
    /** @brief Raised when LeaveGame finishes. */
    System::EventHandler<LeaveGameCompletedEventArgs> LeaveGameCompleted;
    /** @brief Raised when GameStep finishes. */
    System::EventHandler<GameStepCompletedEventArgs> GameStepCompleted;
    /** @brief Raised when GetGameState finishes. */
    System::EventHandler<GetGameStateCompletedEventArgs> GetGameStateCompleted;
    /** @brief Raised when GetAvailableGames finishes. */
    System::EventHandler<GetAvailableGamesCompletedEventArgs> GetAvailableGamesCompleted;
    /** @brief Raised when NewGame finishes. */
    System::EventHandler<NewGameCompletedEventArgs> NewGameCompleted;
    /** @brief Raised when ResetTimeout finishes. */
    System::EventHandler<ResetTimeoutCompletedEventArgs> ResetTimeoutCompleted;
    /** @brief Raised when GetScoreCard finishes. */
    System::EventHandler<GetScoreCardCompletedEventArgs> GetScoreCardCompleted;

    /**
     * @brief Creates a proxy to an endpoint.
     *
     * @param endpointAddress Where the service is. Defaults to the address the original's
     *                        ServiceReferences.ClientConfig names.
     */
    explicit YachtServiceClient(
        const std::string& endpointAddress = "http://localhost:8888/GameServer/")
        : endpointAddress_(endpointAddress),
          channel_(System::ServiceModel::BasicHttpBinding(),
                   System::ServiceModel::EndpointAddress(endpointAddress), "http://tempuri.org/",
                   "IYachtService")
    {
    }

    /**
     * @brief Where this proxy's endpoint is.
     *
     * @return The address, as the original's `Endpoint.Address.ToString()` gives it.
     */
    [[nodiscard]] const std::string& getEndpointAddressProperty() const
    {
        return endpointAddress_;
    }

    /**
     * @brief Registers this client with the server.
     *
     * @param clientURI Where the server should send this client's notifications.
     * @param name      The player's name.
     * @param playerID  A previous session's ID to reclaim, or -1 for a new player.
     */
    void RegisterAsync(const System::Uri& clientURI, const std::string& name, int playerID)
    {
        const std::string uri = clientURI.ToString();
        Start([this, uri, name, playerID] {
            RegisterCompletedEventArgs args;
            args.Result = -1;
            try {
                const auto result = channel_.Invoke("Register", [&](System::Xml::XmlWriter& w) {
                    w.WriteElementString("clientURI", uri);
                    w.WriteElementString("name", name);
                    w.WriteElementString("playerID", std::to_string(playerID));
                });
                args.Result = result.has_value() ? std::stoi(*result) : -1;
            } catch (...) {
                args.Error = std::current_exception();
            }
            Queue([this, args] { RegisterCompleted.Raise(nullptr, args); });
        });
    }

    /**
     * @brief Drops this client's registration.
     *
     * @param sessionID The session to drop.
     */
    void UnregisterAsync(int sessionID)
    {
        StartVoid("Unregister", UnregisterCompleted, [sessionID](System::Xml::XmlWriter& w) {
            w.WriteElementString("sessionID", std::to_string(sessionID));
        });
    }

    /**
     * @brief Joins a game that is waiting for players.
     *
     * @param gameID    The game to join.
     * @param sessionID The joining player's session.
     */
    void JoinGameAsync(const System::Guid& gameID, int sessionID)
    {
        const std::string id = gameID.ToString();
        Start([this, id, sessionID] {
            JoinGameCompletedEventArgs args;
            try {
                const auto result = channel_.Invoke("JoinGame", [&](System::Xml::XmlWriter& w) {
                    w.WriteElementString("gameID", id);
                    w.WriteElementString("sessionID", std::to_string(sessionID));
                });
                args.Result = result.has_value() && ParseBoolean(*result);
            } catch (...) {
                args.Error = std::current_exception();
            }
            Queue([this, args] { JoinGameCompleted.Raise(nullptr, args); });
        });
    }

    /**
     * @brief Leaves the game this player is in.
     *
     * @param sessionID The leaving player's session.
     */
    void LeaveGameAsync(int sessionID)
    {
        Start([this, sessionID] {
            LeaveGameCompletedEventArgs args;
            try {
                const auto result = channel_.Invoke("LeaveGame", [&](System::Xml::XmlWriter& w) {
                    w.WriteElementString("sessionID", std::to_string(sessionID));
                });
                args.Result = result.has_value() && ParseBoolean(*result);
            } catch (...) {
                args.Error = std::current_exception();
            }
            Queue([this, args] { LeaveGameCompleted.Raise(nullptr, args); });
        });
    }

    /**
     * @brief Reports one player scoring one line.
     *
     * @param gameID    The game the step belongs to.
     * @param sessionID The stepping player's session.
     * @param scoreLine Which line was scored.
     * @param score     The score placed on it.
     * @param player    The index of the player who stepped.
     * @param step      The step's sequence number within the game.
     */
    void GameStepAsync(const System::Guid& gameID, int sessionID, int scoreLine,
                       SharpRuntime::bytecs score, int player, int step)
    {
        const std::string id = gameID.ToString();
        StartVoid("GameStep", GameStepCompleted,
                  [id, sessionID, scoreLine, score, player, step](System::Xml::XmlWriter& w) {
                      w.WriteElementString("gameID", id);
                      w.WriteElementString("sessionID", std::to_string(sessionID));
                      w.WriteElementString("scoreLine", std::to_string(scoreLine));
                      w.WriteElementString("score", std::to_string(static_cast<int>(score)));
                      w.WriteElementString("player", std::to_string(player));
                      w.WriteElementString("step", std::to_string(step));
                  });
    }

    /**
     * @brief Asks for the current state of a game.
     *
     * @param gameID    The game to ask about.
     * @param sessionID The asking player's session.
     */
    void GetGameStateAsync(const System::Guid& gameID, int sessionID)
    {
        const std::string id = gameID.ToString();
        StartBytes("GetGameState", GetGameStateCompleted,
                   [id, sessionID](System::Xml::XmlWriter& w) {
                       w.WriteElementString("gameID", id);
                       w.WriteElementString("sessionID", std::to_string(sessionID));
                   });
    }

    /**
     * @brief Asks which games are waiting for players.
     *
     * @param sessionID The asking player's session.
     */
    void GetAvailableGamesAsync(int sessionID)
    {
        StartBytes("GetAvailableGames", GetAvailableGamesCompleted,
                   [sessionID](System::Xml::XmlWriter& w) {
                       w.WriteElementString("sessionID", std::to_string(sessionID));
                   });
    }

    /**
     * @brief Creates a game and joins it.
     *
     * @param sessionID The creating player's session.
     * @param name      The game's name.
     */
    void NewGameAsync(int sessionID, const std::string& name)
    {
        StartBytes("NewGame", NewGameCompleted, [sessionID, name](System::Xml::XmlWriter& w) {
            w.WriteElementString("sessionID", std::to_string(sessionID));
            w.WriteElementString("name", name);
        });
    }

    /**
     * @brief Tells the server the player is still there.
     *
     * @param gameID    The game the player is in.
     * @param sessionID The player's session.
     */
    void ResetTimeoutAsync(const System::Guid& gameID, int sessionID)
    {
        const std::string id = gameID.ToString();
        StartVoid("ResetTimeout", ResetTimeoutCompleted,
                  [id, sessionID](System::Xml::XmlWriter& w) {
                      w.WriteElementString("gameID", id);
                      w.WriteElementString("sessionID", std::to_string(sessionID));
                  });
    }

    /**
     * @brief Asks for the player's own score card.
     *
     * @param sessionID The asking player's session.
     */
    void GetScoreCardAsync(int sessionID)
    {
        StartBytes("GetScoreCard", GetScoreCardCompleted,
                   [sessionID](System::Xml::XmlWriter& w) {
                       w.WriteElementString("sessionID", std::to_string(sessionID));
                   });
    }

    /**
     * @brief Raises the completion events of every operation that has finished.
     *
     * Called from the game's own thread, once per frame. Nothing is raised anywhere else.
     */
    void DispatchPendingCompletions()
    {
        std::vector<std::function<void()>> ready;
        {
            const std::lock_guard<std::mutex> lock(mutex_);
            ready.swap(pending_);
            // A task that has finished is holding nothing worth keeping.
            std::erase_if(running_, [](const System::Threading::Tasks::Task& task) {
                return task.getIsCompletedProperty();
            });
        }

        for (auto& completion : ready) {
            completion();
        }
    }

private:
    static bool ParseBoolean(const std::string& text)
    {
        return text == "true" || text == "True" || text == "TRUE";
    }

    void Queue(std::function<void()> completion)
    {
        const std::lock_guard<std::mutex> lock(mutex_);
        pending_.push_back(std::move(completion));
    }

    void Start(std::function<void()> work)
    {
        const std::lock_guard<std::mutex> lock(mutex_);
        running_.push_back(System::Threading::Tasks::Task::Run(std::move(work)));
    }

    // The two shapes that repeat: an operation with no result, and one returning byte[].
    void StartVoid(const std::string& operation,
                   System::EventHandler<AsyncCompletedEventArgs>& completed,
                   std::function<void(System::Xml::XmlWriter&)> writeParameters)
    {
        Start([this, operation, &completed, writeParameters] {
            AsyncCompletedEventArgs args;
            try {
                (void)channel_.Invoke(operation, writeParameters);
            } catch (...) {
                args.Error = std::current_exception();
            }
            Queue([&completed, args] { completed.Raise(nullptr, args); });
        });
    }

    void StartBytes(const std::string& operation,
                    System::EventHandler<AsyncCompletedEventArgsT<ByteArrayResult>>& completed,
                    std::function<void(System::Xml::XmlWriter&)> writeParameters)
    {
        Start([this, operation, &completed, writeParameters] {
            AsyncCompletedEventArgsT<ByteArrayResult> args;
            try {
                const auto result = channel_.Invoke(operation, writeParameters);
                // A null byte[] comes back as no result element at all, and the game reads it
                // as "the game is gone" -- so the absence has to survive to the handler rather
                // than being flattened into an empty array.
                if (result.has_value() && !result->empty()) {
                    args.Result = System::Convert::FromBase64String(*result);
                }
            } catch (...) {
                args.Error = std::current_exception();
            }
            Queue([&completed, args] { completed.Raise(nullptr, args); });
        });
    }

    std::string endpointAddress_;
    System::ServiceModel::Channels::SoapChannel channel_;

    std::mutex mutex_;
    std::vector<std::function<void()>> pending_;
    std::vector<System::Threading::Tasks::Task> running_;
};

} // namespace YachtServices
