// SPDX-License-Identifier: MS-PL

#pragma once

#include <utility>

#include "Microsoft/Xna/Framework/Matrix.hpp"
#include "Microsoft/Xna/Framework/Vector3.hpp"
#include "Microsoft/Xna/Framework/Graphics/BasicEffect.hpp"
#include "Microsoft/Xna/Framework/Graphics/BlendState.hpp"
#include "Microsoft/Xna/Framework/Graphics/DepthStencilState.hpp"
#include "Microsoft/Xna/Framework/Graphics/GraphicsDevice.hpp"
#include "Microsoft/Xna/Framework/Graphics/Model.hpp"
#include "Microsoft/Xna/Framework/Graphics/ModelMesh.hpp"
#include "Microsoft/Xna/Framework/Graphics/SamplerState.hpp"
#include "Microsoft/Xna/Framework/Graphics/Texture2D.hpp"
#include "Microsoft/Xna/Framework/Graphics/TextureAddressMode.hpp"

namespace GeneratedGeometry
{
    namespace ContentReaders
    {
        class SkyReader;
    }

    using namespace Microsoft::Xna::Framework;
    using namespace Microsoft::Xna::Framework::Graphics;

    /** @brief Holds and renders the skydome generated by the original XNA content pipeline. */
    class Sky
    {
        friend class ContentReaders::SkyReader;

        Model model_;
        Texture2D texture_;

        static SamplerState CreateWrapUClampV()
        {
            SamplerState state;
            state.setAddressUProperty(TextureAddressMode::Wrap);
            state.setAddressVProperty(TextureAddressMode::Clamp);
            return state;
        }

        inline static const SamplerState WrapUClampV = CreateWrapUClampV();

        Sky(Model model, Texture2D texture)
            : model_(std::move(model))
            , texture_(std::move(texture))
        {
        }

    public:
        /** @brief Constructs an empty sky for content deserialization. */
        Sky() = default;

        /**
         * @brief Draws the skydome at the far clip plane.
         *
         * @param view Current camera view matrix.
         * @param projection Current camera projection matrix.
         */
        void Draw(Matrix view, Matrix projection)
        {
            GraphicsDevice& device = *texture_.getGraphicsDeviceProperty();

            device.setDepthStencilStateProperty(DepthStencilState::DepthRead);
            device.getSamplerStatesProperty()[0] = WrapUClampV;
            device.setBlendStateProperty(BlendState::Opaque);

            view.setTranslationProperty(Vector3::Zero);

            projection.M13 = projection.M14;
            projection.M23 = projection.M24;
            projection.M33 = projection.M34;
            projection.M43 = projection.M44;

            for (ModelMesh* mesh : model_.getMeshesProperty())
            {
                for (Effect* effect : mesh->getEffectsProperty())
                {
                    auto* basicEffect = static_cast<BasicEffect*>(effect);
                    basicEffect->setViewProperty(view);
                    basicEffect->setProjectionProperty(projection);
                    basicEffect->setTextureProperty(&texture_);
                    basicEffect->setTextureEnabledProperty(true);
                }

                mesh->Draw();
            }

            device.setDepthStencilStateProperty(DepthStencilState::Default);
            device.getSamplerStatesProperty()[0] = SamplerState::LinearWrap;
        }
    };
}
