// SPDX-License-Identifier: MS-PL

#pragma once

#include <cstdint>
#include <vector>

#include "Graphics/TangentVertex.hpp"

namespace RacingGame::Tracks
{
    class TrackLine;

    /**
     * @brief Owns the CPU road meshes generated by the original Track class.
     */
    class TrackGeometry
    {
    public:
        /**
         * @brief Generates road, back-hull and tunnel meshes from a track line.
         *
         * @param trackLine Fully generated source track line.
         */
        explicit TrackGeometry(const TrackLine& trackLine);

        /** @brief Gets road-surface vertices. */
        [[nodiscard]] const std::vector<Graphics::TangentVertex>&
        getRoadVerticesProperty() const;
        /** @brief Gets road-surface triangle indices. */
        [[nodiscard]] const std::vector<std::int32_t>&
        getRoadIndicesProperty() const;
        /** @brief Gets back-hull vertices. */
        [[nodiscard]] const std::vector<Graphics::TangentVertex>&
        getRoadBackVerticesProperty() const;
        /** @brief Gets back-hull triangle indices. */
        [[nodiscard]] const std::vector<std::int32_t>&
        getRoadBackIndicesProperty() const;
        /** @brief Gets tunnel vertices. */
        [[nodiscard]] const std::vector<Graphics::TangentVertex>&
        getRoadTunnelVerticesProperty() const;
        /** @brief Gets tunnel triangle indices. */
        [[nodiscard]] const std::vector<std::int32_t>&
        getRoadTunnelIndicesProperty() const;

    private:
        static constexpr float RoadBackHullTextureWidthFactor = 1.0f;
        static constexpr float RoadTunnelTextureWidthFactor = 0.25f;
        static constexpr float RoadBackSideTextureHeight = 0.135f;
        static constexpr float RoadTunnelSideTextureHeight = 0.235f;

        std::vector<Graphics::TangentVertex> roadVertices;
        std::vector<std::int32_t> roadIndices;
        std::vector<Graphics::TangentVertex> roadBackVertices;
        std::vector<std::int32_t> roadBackIndices;
        std::vector<Graphics::TangentVertex> roadTunnelVertices;
        std::vector<std::int32_t> roadTunnelIndices;
    };
}
