# Optional framework modules follow the selected samples' declared link requirements.
function(cna_samples_require_gamer_services output source_root)
    if(NOT ARGN)
        # The unrestricted corpus includes networking and Gamer Services samples.
        set(${output} ON PARENT_SCOPE)
        return()
    endif()
    set(required OFF)
    foreach(sample IN LISTS ARGN)
        set(declaration "${source_root}/samples/${sample}/CMakeLists.txt")
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${declaration}")
        file(READ "${declaration}" contents)
        string(REGEX REPLACE "#[^\n]*" "" contents "${contents}")
        if(contents MATCHES "(^|[ \t\r\n(])(NET|GAMER_SERVICES)([ \t\r\n)]|$)")
            set(required ON)
        endif()
    endforeach()
    set(${output} ${required} PARENT_SCOPE)
endfunction()
